basePath: /api
info:
  contact: {}
  description: API for managing Users
  title: User Management API
  version: "1.0"
paths:
  /auth/callback:
    get:
      description: Handles the callback from Cognito after authentication.
      parameters:
      - description: Authorization code
        in: query
        name: code
        required: true
        type: string
      responses:
        "302":
          description: Redirects to the frontend URL after successful login.
        "400":
          description: Authorization code missing
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Cognito Callback
      tags:
      - authentication
  /auth/check:
    get:
      description: Checks if the user is authenticated based on the ID token in cookies.
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Authentication Check
      tags:
      - authentication
  /auth/logout:
    get:
      description: Logs out the user by clearing authentication cookies.
      responses:
        "302":
          description: Redirects to the frontend URL after successful logout.
      summary: Logout Callback
      tags:
      - authentication
  /auth/refresh:
    post:
      description: Refreshes the ID token using the refresh token stored in cookies.
      responses:
        "200":
          description: Token refreshed successfully!
          schema:
            type: string
        "401":
          description: Refresh token missing or invalid
          schema:
            type: string
      summary: Token Refresh
      tags:
      - authentication
  /health:
    get:
      description: Returns the health status of the API.
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - health
swagger: "2.0"
